name: 信用卡还款提醒

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  check-and-remind:
    runs-on: ubuntu-latest
    steps:
      - name: 发送还款提醒
        run: |
          curl -s -X GET "https://sctapi.ftqq.com/SCT375269TFa3bf2xcU2GvBaowy4zxmAcs.send?title=信用卡还款提醒&desp=您的信用卡已到期请尽快还款"
